### ISSUE TITLE
avoid high buffer allocations in linkSort

### ISSUE THREAD

**Issue by mcollina** [ipld/js-ipld-dag-pb#107]
In `linkSort` https://github.com/ipld/js-ipld-dag-pb/blob/39cfef1757f733649afcd00bfd02b64270145b4b/src/dag-node/util.js#L27-L32, 2 new buffers are allocated for each comparison. When sorting a big array (100+ entries, which seems common), this is going to create very high gc pressure.
Ideally a sort implementation should not allocate any new objects at all. 

See #104 for a bigger discussion on the sorting logic.

**Comment by achingbrain** [comment]
`link.name` should be a string so I wonder why it doesn't just use `String.prototype.localeCompare()`

@vmx any ideas?

**Comment by vmx** [comment]
It could be related to the Go implementation. We should use the same algorithm in all implementations.
