### ISSUE TITLE
deserialization calls serialize

### ISSUE THREAD

**Issue by mcollina** [ipld/js-ipld-dag-pb#109]
In the [`deserialize`](https://github.com/ipld/js-ipld-dag-pb/blob/d56ed9a3afb71b0aeb735da5add7e1feeb7c6349/src/util.js#L78-L88) method, it calls [`serialize`](https://github.com/ipld/js-ipld-dag-pb/blob/d56ed9a3afb71b0aeb735da5add7e1feeb7c6349/src/dag-node/create.js#L33-L35) internally. Why is it doing it? It seems quite an expensive operation, and if we already have the data serialized, why serializing it back again? We might be able to speed things quite a bit if we avoided that.

https://upload.clinicjs.org/public/4ba0640c671dd4a618e486e9010abe537d82bb4be5d5ca3464c72445c7a22cae/53064.clinic-flame.html#selectedNode=5121&zoomedNode=5121&exclude=3e&merged=true

![schermata 2018-12-10 alle 19 07 59](https://user-images.githubusercontent.com/52195/49751889-ef0e4900-fcae-11e8-9708-ba785ee222e3.png)

(this comes from https://github.com/ipfs/benchmarks/blob/master/tests/local-extract.js benchmark)

**Comment by mikeal** [comment]
pinging @vmx who is re-writing the IPLD interface to address some of the unnecessary serialize/deserialize calls we tend to make.

**Comment by achingbrain** [comment]
That was refactored out a while ago, might not have made it into a js-ipfs release yet though.

**Comment by mcollina** [comment]
Good to know! Closing.

I'd recommend to release that asap.

**Comment by achingbrain** [comment]
@mcollina you could try ipfs@0.34.0-pre.0 and see if the problem still exists? It has the latest ipld-dag-pb in it. May have random breakage of course.

**Comment by achingbrain** [comment]
Aha, missed your comment - it’ll be in the impending v0.34.0 release.
