### ISSUE TITLE
Remove DAGNode.create?

### ISSUE THREAD

**Issue by achingbrain** [ipld/js-ipld-dag-pb#132]
Sort of related to #131 but if `DAGNode.create` can now calculate the serialized size of a node synchronously, why not do that in the `DAGNode` constructor if the serialized size is not passed and remove the `.create` function?

**Comment by vmx** [comment]
I had a look. the problem is that we would need to call `serialize()` which does a call to `DAGNode.isDAGNode()`. So you'd have a circular reference that would make things fail.

**Comment by achingbrain** [comment]
It only does a call to `DAGNode.isDAGNode()` to find out if the `data` argument passed to `util.serialize` is a `DAGNode`, which it should not be if we are in the constructor of `DAGNode` outside of programmer error so that could be factored out and you'd have an internal `_serialize` function that did the same thing as `util.serialize` just without that check which `util.serialize` would call.

...

Anyway I've found this is only a concern when creating trees of `DAGNode`s and `DAGLink`s prior to serialization so we don't even know the serialized size at that point.

We only assert on serialized size in the DAGNode constructor if it's non-zero in order to do this sort of thing:

```javascript
const node = new DAGNode(buf, links, 0) // dunno
```

How about defaulting it (and the links?) in the constructor?

```javascript
class DAGNode {
  constructor (data, links = [], serializedSize = 0) {
    if (serializedSize !== 0) {
      assert(serializedSize, 'A DAGNode requires it\'s serialized size')
    }
...
```

This way you can use `new DAGNode(...)` and `new DAGLink(...)` symmetrically, ditch the `DAGNode.create` method and you don't need the weird `0` argument at the end of the `DAGNode` constructor.

If fact you could probably remove the `assert` from the constructor entirely as it seems pretty low value at this point.
