### ISSUE TITLE
Made DAGNodes mutable?

### ISSUE THREAD

**Issue by achingbrain** [ipld/js-ipld-dag-pb#136]
Given that a `DAGNode` no longer knows about it's `CID`, keeping it immutable seems like overkill (and also a lie since you can mutate the `.links` and `.data` content, add new properties, etc).

You could lose the `.addLink`, `.removeLink`, `.clone`, etc methods too then.

**Comment by vmx** [comment]
DAGnodes are mutable now (with the merge of https://github.com/ipld/js-ipld-dag-pb/pull/141).
