### ISSUE TITLE
Perf: Don't hide 'private' fields?

### ISSUE THREAD

**Issue by achingbrain** [ipld/js-ipld-dag-pb#152]
It's expensive and the convention in js is to leave methods/properties prefixed by `_` alone.

![image](https://user-images.githubusercontent.com/665810/60196548-b0e90900-983d-11e9-87a9-46790f7b2b69.png)

Consider removing this?

**Comment by achingbrain** [comment]
Enumerable getters too.  Less expensive, but do we need to do it like this?

![image](https://user-images.githubusercontent.com/665810/60199555-7e8eda00-9844-11e9-8019-a95722524846.png)

**Comment by vmx** [comment]
The reason for having those is that you can easily have the `tree()` function that doens't need to do any work, but just iterate over things. The other advantage is that also in your code you can enumerate over all properties and just get the values you resolve to.

Can you tell me more about those graphics? Where are they from? How much of a bottleneck is that compared to e.g. deserializing the PB.

Is this a huge performance hit or a "we could be faster if we won't do this, but atm it doesn't really matter"?
