### ISSUE TITLE
Prevent double serialization

### ISSUE THREAD

**Issue by vmx** [ipld/js-ipld-dag-pb#154]
This is a followup of https://github.com/ipld/js-ipld-dag-pb/pull/141#pullrequestreview-263570966.

`toDagLink()` should double serialize things. Best would be if `size` would be removed from DAGLink. Though this is a change that impacts UnixFS.

**Comment by achingbrain** [comment]
I don't think this is necessary any more because IPFS now does skips `js-ipld` when serializing `dag-pb` nodes and passes blocks to the block service directly.

Also it was decided to not remove `.tsize` after all.
