### ISSUE TITLE
Some security findings

### ISSUE THREAD

**Issue by aileenscott-uleska** [ipld/js-ipld-dag-pb#185]
Hi folks,

I hope you don’t mind, we were testing out our security automation tool and ran it against your project.  A few issues came out that you may want to check out - we weren’t sure how to submit a PDF here, so we uploaded it to https://source-security.co.uk/46636f7a-fb13-4f5a-81e1-330787a79805/ if you wanna check it out.

Any issues or feedback, just let us know.

Aileen

**Comment by rvagg** [comment]
please don't, this is not useful, reporting as spam
