### ISSUE TITLE
toJSON should follow the spec

### ISSUE THREAD

**Issue by wanderer** [ipld/js-ipld-dag-pb#38]
it would be nice if toJSON followed the [ipld compat protobuf spec](https://github.com/ipld/specs/blob/master/ipld/ipld-compat-protobuf.md)

currently it produces object like 
```
{
  data: <Buffer>,
  size: Int,
  mutltihash: String
  links: [
    {
      size: Int,
      name: String
      mutltihash: String
    }
 ]
}
```
multihash should change to link : {'/': <hash>}
and the top level mutilhash is unessacry

**Comment by vmx** [comment]
I'm closing this issue in favour of the more general https://github.com/ipld/interface-ipld-format/issues/49.
