### ISSUE TITLE
Interop with Go got broken (now fixed by unpublishing latest patch version)

### ISSUE THREAD

**Issue by diasdavid** [ipld/js-ipld-dag-pb#41]
I completely missed this comment https://github.com/ipld/js-ipld-dag-pb/pull/39#discussion_r137020214 and given this issue reported here https://github.com/ipld/js-ipld-dag-pb/pull/39/files#r137020214, now two objects created with the same data and or links will have different hashes between go and js. As expected, this is not ok.

As an interim solution, I'll unpublish the latest version and will publish again once everything needed for https://github.com/ipfs/js-ipfs/issues/991 is ready.

**Comment by dignifiedquire** [comment]
there is an easier quick fix, you can change the generated file manually to match

**Comment by dignifiedquire** [comment]
Probably need to recheck the other modules as well..

**Comment by diasdavid** [comment]
Only two got released from the list https://github.com/ipfs/js-ipfs/issues/991. I unpublished those 2 patch versions. Let's finish the endeavour, make sure everything is ready and super tested (all the way to js-ipfs running js-ipfs interop tests) and then we will merge.
