### ISSUE TITLE
Resolving through link names

### ISSUE THREAD

**Issue by osarrouy** [ipld/js-ipld-dag-pb#71]
Hey everyone.

I'm kind of stuck on something. I'm trying to write an IPLD resolver for a custom ethereum-based git-like protocol i'm writing. For that reason i would like to use the keccak-256 hash algorithm for my hashes - to perform on chain verification.

I've had a look at ipld-dag-pb - which may use this algorithm - but the resolving process is not quite human friendly. I'd like to be able to resolve through resolve(node, /parents/0/) for instance and not through resolve(node, Links/name/ ....).

I saw this comment on the code: 

```
// TODO by enabling something to resolve through link name, we are
 // applying a transformation (a view) to the data, confirm if this
// is exactly what we want
```
Would you be open to such a thing ?

**Comment by vmx** [comment]
It sounds like you want to write a custom IPLD Format implementation. You could have a look at the Bitcoin Format implementation https://github.com/ipld/js-ipld-bitcoin which should be simpler to follow than dag-pb.

**Comment by osarrouy** [comment]
Hey !

Thanks a lot for your answer !

I've already tried that. The problem I have is to pick a codec for ```new CID(1, codec, multihash)``` part of the util.cid function. I can't use a custom codec since it's not in the multicodec table and if I use an already existing one, i can't use keccak-256 :(

Any idea ?

**Comment by osarrouy** [comment]
In fact when i use a custom codec such as ```new CID(1, codec, multihash)``` then, when I try to get the buffer or the baseEncodedString of the CID I got the following error :
```
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
```

Does it come from the multicodec table or is it something else ?

Thanks a lot !

**Comment by vmx** [comment]
I needed to play around with it myself, and I hope what I found out help you.

With some online tool I created a kecccak-256 hash, which is: `3ea2f1d0abf3fc66cf29eebb70cbd4e7fe762ef8a09bcc06c8edf641230afec0`.  I then used https://github.com/multiformats/js-multihash to convert it to a base58 encoded string:
```
> mh.toB58String(mh.encode(Buffer.from('3ea2f1d0abf3fc66cf29eebb70cbd4e7fe762ef8a09bcc06c8edf641230afec0'), 'keccak-256', 64))
'Bcd1XP9RvQLefavoxvgNB9vhA7aLhkxDUdjewpPc5NkXk8ocPsSMzaPY4ywZ1LvWQFFiPHSzWdeCFcscBM9GzSeh4j'
```

If you use that one as a CID you get that it's a dag-pb node: http://cid-utils.ipfs.team/#Bcd1XP9RvQLefavoxvgNB9vhA7aLhkxDUdjewpPc5NkXk8ocPsSMzaPY4ywZ1LvWQFFiPHSzWdeCFcscBM9GzSeh4j
The important information here is that it is a `cidv0`, but I wanted a `cidv1`.

To get there I used the Buffer of the js-multihash encoded value:

```
> mh.toHexString(mh.encode(Buffer.from('3ea2f1d0abf3fc66cf29eebb70cbd4e7fe762ef8a09bcc06c8edf641230afec0'), 'keccak-256', 64))
'1b4033656132663164306162663366633636636632396565626237306362643465376665373632656638613039626363303663386564663634313233306166656330'
```

Took that output for my CID generation (with https://github.com/ipld/js-cid):

```
> new CID(1, 'keccak-256', Buffer.from('1b4033656132663164306162663366633636636632396565626237306362643465376665373632656638613039626363303663386564663634313233306166656330', 'hex'))
CID {
  codec: 'keccak-256',
  version: 1,
  multihash: <Buffer 1b 40 33 65 61 32 66 31 64 30 61 62 66 33 66 63 36 36 63 66 32 39 65 65 62 62 37 30 63 62 64 34 65 37 66 65 37 36 32 65 66 38 61 30 39 62 63 63 30 36 ... > }
```

That looks already promising. I then wanted a CID I can put into the cid-utils online tool:

```
> new CID(1, 'keccak-256', Buffer.from('1b4033656132663164306162663366633636636632396565626237306362643465376665373632656638613039626363303663386564663634313233306166656330', 'hex')).toBaseEncodedString()
'z9Pi35Y51AmKw4oDinTRtRLYRbvrViJgCfEfHZuW4KNWREDNeTxgRvjAnwSpsydeVuALtaUVZtFdTQkQjvSZp4EJ6tn6K'
```

http://cid-utils.ipfs.team/#z9Pi35Y51AmKw4oDinTRtRLYRbvrViJgCfEfHZuW4KNWREDNeTxgRvjAnwSpsydeVuALtaUVZtFdTQkQjvSZp4EJ6tn6K

So now it's at least a `cidv1` keccak-256 encoded value and not a pb-dag node anymore.

I know that what you really want is your own custom Mulicodec. I currently run out of time, but I'll have a look at it soon.

**Comment by osarrouy** [comment]
Hey @vmx !

Thanks a lot for your feedback !

I've worked on it a little on my side also and found where the problem come from : https://github.com/ipld/js-cid/blob/4d7bcf860214fef04700ebe338908d36182c931e/src/index.js#L123

If i try to create my own multicodec the js-cid library tries to lookup something which does not exist in the multicodec table and raises an error.

For now the only solution i've come up with is the name my format with an existing format name (e.g raw) and replace the raw format resolver in the wrapping ipld resolver library (with support.rm and support.add)

Do you think it can be a good workaround at least for tests ?

Bests.

**Comment by vmx** [comment]
@osarrouy I'm currently working on it. Expect some PRs (which you could then apply locally) later today. You'd then be able to add your own custom codec.

**Comment by osarrouy** [comment]
@vmx ! Wow ! Ok. Thanks a lot. Really :)

**Comment by vmx** [comment]
This PR should implement the functionality you need: https://github.com/multiformats/js-multicodec/pull/25

**Comment by osarrouy** [comment]
@vmx Thanks a lot !

**Comment by vmx** [comment]
@osarrouy I'm closing this issue as I think it is solved. If not, please re-open it.

**Comment by osarrouy** [comment]
That's all good :)
