### ISSUE TITLE
Support CIDs in dag-pb links

### ISSUE THREAD

**Issue by olizilla** [ipld/js-ipld-dag-pb#79]
js-ipld-dag-pb assumes that links will be multihashes
https://github.com/ipld/js-ipld-dag-pb/blob/70b0cd53148fa26dc3e75fe250c0f1ad8161a59e/src/dag-link/index.js#L8-L23

Here is a dag-pb node where one of the links is a CIDv1
https://ipfs.io/api/v0/dag/get?arg=QmViWi5az9iiPzESM6ruHf84TcmHSAVQ2KQdNveoDH7eaY/refs/heads

```
// 20180731162407
// https://ipfs.io/api/v0/dag/get?arg=QmViWi5az9iiPzESM6ruHf84TcmHSAVQ2KQdNveoDH7eaY/refs/heads

{
  "data": "CAE=",
  "links": [
    {
      "Name": "archive",
      "Size": 83,
      "Cid": {
        "/": "QmfBgo8BAB26hFtyGNGK46rqYkKLFvWYfTqjrGdbUEjnUU"
      }
    },
    {
      "Name": "master",
      "Size": 42,
      "Cid": {
        "/": "z8mWaJHXieAVxxLagBpdaNWFEBKVWmMiE"
      }
    }
  ]
}
```

I assume we need to upgrade `DagLink` to support CIDs, but I've never seen one like that before, so I first want to verify that such a thing _should_ be possible.

**Comment by vmx** [comment]
@diasdavid, @Stebalien Can you help?

**Comment by Stebalien** [comment]
Yes, they can be CIDv1 links. Specifically, unixfs can store CIDv1 pointers to *raw* blocks. That's how we implement the raw leaves feature (where we store file chunks as raw data instead of wrapping them in protobufs).
