### ISSUE TITLE
Improve perf of linkSort

### ISSUE THREAD

**Issue by diasdavid** [ipld/js-ipld-dag-pb#8]
https://github.com/ipld/js-ipld-dag-pb/blob/master/src/dag-node/util.js#L24-L26

//cc @dignifiedquire

**Comment by vmx** [comment]
Not sure what this really is about it refers to https://github.com/ipld/js-ipld-dag-pb/blob/2b1a356ba748f6a340b4fa98c95a8ed525f1c0b9/src/dag-node/util.js#L24-L26.

@diasdavid if you think it is still an issue, please re-open with more information.
