### ISSUE TITLE
Resolving Link Name and/or Tsize

### ISSUE THREAD

**Issue by alanshaw** [ipld/js-ipld-dag-pb#85]
Is this code correct?

https://github.com/ipld/js-ipld-dag-pb/blob/aa6274c14443003662423dcefb26573c2480f3aa/src/resolver.js#L61-L64

The resolved value is `{ "/": "name.txt" }` or `{ "/": 12345 }` - shouldn't it only have the object with slash property wrapper if it's a link?

**Comment by diasdavid** [comment]
Yeah, that's a bug. @alanshaw can you write tests for these and a PR with a fix?

**Comment by alanshaw** [comment]
Yep!
