### ISSUE TITLE
Skip sorting links when deserializing?

### ISSUE THREAD

**Issue by achingbrain** [ipld/js-ipld-dag-pb#97]
At the moment when deserializing a protobuf we [pass](https://github.com/ipld/js-ipld-dag-pb/blob/master/src/util.js#L75) the links into `DAGNode.create` which in turn [passes](https://github.com/ipld/js-ipld-dag-pb/blob/master/src/dag-node/create.js#L39) them to [linkSort](https://github.com/ipld/js-ipld-dag-pb/blob/master/src/dag-node/util.js#L24-L29).

When you have DAGNodes with lots of links being queried repeatedly this can take up a non-trivial amount of time.

I think we should be able to skip the sorting.  My reasoning is:

1. We're deserializing the DAGNode from the buffer that corresponds to it's CID, so the links should have been sorted already
2. If the links were not sorted, serializing the DAGNode with sorted links would result in one with a different CID as the serialized bytes would be in a different order

Any thoughts @ipld/javascript-team ?

**Comment by achingbrain** [comment]
By way of example [linkSort](https://github.com/ipld/js-ipld-dag-pb/blob/master/src/dag-node/util.js#L24-L29) is passed to [stable](https://www.npmjs.com/package/stable) during `DAGNode.create`:

![image](https://user-images.githubusercontent.com/665810/47733276-c763a400-dc5f-11e8-8859-bf59aa796c00.png)

**Comment by vmx** [comment]
I agree that the sorting step should be skipped. I hope I'm not missing something here :)

**Comment by achingbrain** [comment]
I think it's only needed if the user is calling `DAGNode.create`, e.g. we can skip it when deserializing existing DAGNodes but not when creating new ones.

I'll put a PR together.

**Comment by diasdavid** [comment]
Sorting is necessary for interop with dag-pb on go-ipfs, but AFAIU just for the serialization step.
